-- audio/init.lua - the soundscape.
--
-- This is an ambient game, so the mix is built the way an ambient record
-- is: one continuous bed that never stops, weather layered over it, and
-- very few one-shots, all quiet. The loudest thing in the game is rain.
--
-- THREE RULES the mix obeys:
--
--   1. Nothing is a notification. There is no ding for "you can act now"
--      and no buzzer for a refusal -- a refused verb gets a soft low thud
--      that says "not now" and nothing more. The game never scolds.
--   2. Per-ant events are RATE LIMITED, hard. At 150 ants a tick for every
--      delivery is a machine gun; it plays at most a few times a second
--      and its volume follows how busy the colony is, so what you hear is
--      the RATE of work rather than each unit of it.
--   3. The bed crossfades at season boundaries and never restarts. The
--      year should feel continuous.
--
-- Everything is generated by tools/make-audio.py -- no third-party audio in
-- the cart, and the whole soundscape is tunable by editing numbers.



local M = {}

M.enabled = true
M.masterVolume = 0.85

local beds = {}          -- season name -> source
local sfx = {}           -- name -> source
local weather = {}       -- name -> source

-- MUSIC, two tracks that answer one question: is anything hostile
-- happening? "Dew on the Meadow" is the default; "Moonlit Skirmish" takes
-- over when an enemy is discovered or fighting starts, then hands back
-- once things settle. Threat-driven rather than level-driven, so the
-- music reacts to what the player is doing rather than to which mission
-- they happen to be on.
local music = {}         -- name -> source
local musicGain = {}     -- name -> current gain
local MUSIC_FADE = 4.0   -- seconds; slower than the bed, it is a mood not a cue
local MUSIC_VOL = 0.42   -- under the bed and well under the sfx
-- How long combat music persists after the last hostile thing. Without
-- this the track flickers back and forth on every skirmish tick.
local TENSE_HOLD = 12.0
local tenseFor = 0

local currentBed = nil
local bedGain = {}       -- season name -> current gain, for the crossfade
local CROSSFADE = 3.0    -- seconds

-- One-shot budget. `cooldown` is the minimum gap in seconds; a sound asked
-- for sooner is DROPPED rather than queued, because a queue would replay a
-- burst of stale events after the burst is over.
local COOLDOWN = {
  link = 0.10,
  refuse = 0.35,
  discover = 0.8,
  season = 0.0,
  threat = 1.5,
  deliver = 0.22,
  -- PLAN 05 SLOWED COMBAT TO ONE SWING PER 3s (was 1s), so the hit RATE
  -- this limiter was shaped for no longer happens: a 40-ant battle is
  -- now ~40 * (1/3) * 0.5 =~ 7 hits/s =~ one per 140ms, well under the
  -- old 70ms floor on its own. Lowered to 30ms -- a polyphony guard
  -- against a pathological ant count rather than the thing doing the
  -- shaping -- so "every hit clangs" holds for any battle a player is
  -- actually looking at, and only a battle far larger than anything the
  -- game currently produces would ever hit the limiter at all.
  clank = 0.03,
}
local lastPlayed = {}

local time = 0

local function tryLoad(path)
  local ok, src = pcall(love.audio.newSource, path)
  if not ok or not src then
    print("@audio MISSING " .. path .. " (" .. tostring(src) .. ")")
    return nil
  end
  return src
end

function M.init()
  -- A host with no audio must not take the game down, so every load is
  -- guarded and a missing file degrades to silence for that one sound.
  for _, name in ipairs({ "spring", "summer", "autumn", "winter" }) do
    beds[name] = tryLoad("sounds/bed-" .. name .. ".ogg")
    bedGain[name] = 0
    if beds[name] and beds[name].setLooping then
      beds[name]:setLooping(true)
    end
  end
  for _, name in ipairs({ "rain", "wind" }) do
    weather[name] = tryLoad("sounds/" .. name .. ".ogg")
    if weather[name] and weather[name].setLooping then
      weather[name]:setLooping(true)
    end
  end
  -- The two music tracks. Long files, so they loop and never restart.
  -- OGG VORBIS, NOT MP3. The engine ships stb_vorbis and no mp3 decoder
  -- at all, so an .mp3 loads as nil and the track is silently absent --
  -- which is exactly how these two arrived.
  -- NO SPACES IN ASSET NAMES. "Dew on the Meadow.ogg" is listed in
  -- assets.index correctly and still fails to load -- the packer or the
  -- loader does not survive the spaces -- so the tracks live beside every
  -- other sound with the project's naming. Original titles: "Dew on the
  -- Meadow" (calm) and "Moonlit Skirmish" (tense).
  for key, file in pairs({ calm = "sounds/music-calm.ogg",
                           tense = "sounds/music-tense.ogg" }) do
    music[key] = tryLoad(file)
    musicGain[key] = 0
    if music[key] and music[key].setLooping then
      music[key]:setLooping(true)
    end
  end

  for _, name in ipairs({ "link", "refuse", "discover", "season", "threat",
                          "deliver", "clank" }) do
    sfx[name] = tryLoad("sounds/" .. name .. ".ogg")
    lastPlayed[name] = -99
  end

  local n = 0
  for _ in pairs(beds) do n = n + 1 end
  print(string.format("@audio init beds=%d sfx=%d weather=%d", n,
        (sfx.link and 1 or 0) + (sfx.season and 1 or 0), (weather.rain and 1 or 0)))
end

-- What the mixer is actually doing, for a gate to assert on.
--
-- This exists because romdev's audioDebug({op:'record'}) captures SILENCE
-- for every wasmcart cart on this server -- including a shipped, human-
-- verified one used as a control -- so a WAV cannot currently prove a cart
-- makes noise. The cart reporting its own live channel state can. Reported
-- in internal-romdev/feedback/2026-08-15_audiodebug-silent-for-wasmcart.md.
function M.report()
  local parts = {}
  for name, src in pairs(beds) do
    if (bedGain[name] or 0) > 0.001 then
      parts[#parts + 1] = string.format("bed:%s=%.2f%s", name, bedGain[name],
        (src.isPlaying and src:isPlaying()) and "P" or "-")
    end
  end
  if (M._rain or 0) > 0.002 then
    parts[#parts + 1] = string.format("rain=%.2f%s", M._rain,
      (weather.rain and weather.rain.isPlaying and weather.rain:isPlaying())
      and "P" or "-")
  end
  if weather.wind and weather.wind.isPlaying and weather.wind:isPlaying() then
    parts[#parts + 1] = "wind=P"
  end
  -- MUSIC IS IN THE REPORT because a gate cannot hear it: romdev captures
  -- silence for every wasmcart cart, so the cart saying which track is up
  -- and at what gain is the only evidence available.
  for key, src in pairs(music) do
    if (musicGain[key] or 0) > 0.001 then
      -- `tell()` is the real evidence: a channel can report "playing"
      -- after its sample ended, so the POSITION is what proves a loop.
      local pos = (src.tell and src:tell()) or -1
      parts[#parts + 1] = string.format("music:%s=%.2f%s@%.0f", key, musicGain[key],
        (src.isPlaying and src:isPlaying()) and "P" or "-", pos)
    end
  end
  parts[#parts + 1] = "war=" .. ((tenseFor or 0) > 0 and "1" or "0")
  parts[#parts + 1] = "shots=" .. tostring(M._shotCount or 0)
  print("@audio " .. table.concat(parts, " "))
end

local function setGain(src, g)
  if src and src.setVolume then
    src:setVolume(math.max(0, math.min(1, g)) * M.masterVolume)
  end
end

-- Start a loop at a given gain, keeping it alive.
--
-- ORDER IS LOAD-BEARING, and getting it wrong made the whole game silent.
-- Source:play() passes the CURRENT self.vol to the host when it allocates
-- the channel; setVolume before there is a channel only records the number
-- for later. So calling play() while the fade gain is still ~0 starts the
-- source at volume zero AND makes isPlaying() true forever after -- the
-- source is then "already playing", never restarted, and inaudible for the
-- rest of the session. Set the gain first, and only start once it is
-- actually above zero.
local function ensurePlaying(src, gain)
  if not src then return end
  if gain <= 0.002 then
    -- SILENT, BUT STILL RUNNING. Returning here without checking left a
    -- faded-out loop's channel unowned: if the host reclaims it the source
    -- is gone for good, and the track only revives on the next fade-UP --
    -- which for the calm music on a peaceful level never comes, so the
    -- music simply stopped and never returned. Keep the channel alive at
    -- zero so a crossfade always has something to fade back to.
    setGain(src, 0)
    local alive = src.isPlaying and src:isPlaying()
    if not alive then
      -- Start it at an inaudible-but-nonzero gain: play() hands the
      -- CURRENT volume to the host when it allocates the channel, and a
      -- literal zero there makes the source "playing" and permanently
      -- silent (see the note above this function).
      setGain(src, 0.0015)
      pcall(function() src:play() end)
      setGain(src, 0)
    end
    return
  end
  setGain(src, gain)
  local playing = src.isPlaying and src:isPlaying()
  if not playing then pcall(function() src:play() end) end
end

-- ── one-shots ──────────────────────────────────────────────────────────
function M.play(name, volume)
  if not M.enabled then return false end
  local src = sfx[name]
  if not src then return false end
  local gap = COOLDOWN[name] or 0.2
  if time - (lastPlayed[name] or -99) < gap then return false end
  lastPlayed[name] = time
  M._shotCount = (M._shotCount or 0) + 1
  -- setVolume BEFORE play: play() hands the current vol to the host when it
  -- allocates the channel (see ensurePlaying for the longer version of this
  -- trap). Stop first so a retrigger restarts from the head instead of
  -- being ignored as already-playing.
  pcall(function() src:stop() end)
  setGain(src, volume or 0.8)
  pcall(function() src:play() end)
  return true
end

-- ── per-frame mix ──────────────────────────────────────────────────────
-- The old sim carried seasons, weather and threats; this one does not.
-- Rather than delete the mixer, its update stands down until the new game
-- grows its own reasons to make noise -- the beds and one-shots are all
-- still here.
local lastHits = 0

function M.update(snap, dt)
  if not M.enabled then return end
  time = time + dt

  -- ── COMBAT: a clank per landed blow, within reason ──
  --
  -- The sim counts hits; this turns the RATE into sound. Volume follows how
  -- big the scrap is, so two ants scuffling is a tick and a twenty-a-side
  -- assault is a proper clatter -- rule 2 of this file (per-ant events are
  -- rate limited, and what you hear is the rate rather than each unit).
  --
  -- The counter only ever grows, so a level change resets it below rather
  -- than firing a burst for a battle on a map that no longer exists.
  -- BUG FOUND LIVE, 2026-08-19: this read `snap.hits`, but `snap` is the
  -- whole sim state (`S`) and the swing counter lives on `S.agents.hits`
  -- (agents.lua's M.fight/M.fightSpider both write `a.hits`, never
  -- `s.hits`) -- so `hits` was permanently 0, `hits > lastHits` never
  -- fired, and no clank ever played, in any real playthrough, silently,
  -- since whenever this branch was written. Every automated gate that
  -- exercises combat reads `a.hits` STRAIGHT off the sim (probe.lua's
  -- own `@m` line), never through this function, which is exactly why
  -- 25+ passing battle-gate assertions never caught it.
  local hits = (snap.agents and snap.agents.hits) or 0
  if hits < lastHits then
    lastHits = hits            -- new world; do not replay the old one's war
  elseif hits > lastHits then
    local d = hits - lastHits
    lastHits = hits
    -- Louder for a bigger exchange, but never a notification: this tops out
    -- well under the one-shots that mean the player did something.
    M.play("clank", math.min(0.55, 0.22 + d * 0.05))
  end

  -- ── MUSIC: are we at war? ──
  --
  -- BOTH TRACKS PLAY FOREVER; only their gains move. Stopping the quiet
  -- one and starting the other would restart it from its head on the way
  -- back, and that seam is audible -- the same reason the seasonal beds
  -- are never stopped either.
  --
  -- WAR IS A FIGHT, NOT A NEIGHBOUR.
  --
  -- This used to be true for any enemy mound that was `observed` -- and
  -- `observed` is set every tick for every neighbour of one of your queened
  -- colonies (sim/init.lua). So on any map where red holds ground next to
  -- yours, which is most of them after the opening, the flag was
  -- PERMANENTLY true and the skirmish track simply never ended. It read as
  -- music that would not stop, because that is exactly what it was.
  --
  -- The honest question is whether a fight is happening: are your ants at
  -- an enemy mound, or enemy ants at yours. `contested` already answers the
  -- first (it is set for any mound your ants are inbound to, and cleared
  -- every tick when they are not), and a hostile ant standing on ground you
  -- hold answers the second. Both end when the fighting does.
  --
  -- TENSE_HOLD still keeps the track up for a while after the last hostile
  -- thing, so a brief skirmish does not flicker the music back and forth --
  -- but now it actually expires.
  local hostile = false
  local w = snap.world
  if w then
    for i = 1, #w.nodes do
      local n = w.nodes[i]
      -- You are assaulting them: your column is inbound to their ground.
      if n.contested and n.owner and n.owner ~= "you" then
        hostile = true
        break
      end
    end
    if not hostile and snap.agents then
      -- ...or they are on top of you: an enemy ant standing on a mound you
      -- hold. That is a raid in progress and it should sound like one.
      local a = snap.agents
      for i = 1, a.n do
        local ant = a.pool[i]
        if ant.side ~= "you" and ant.at then
          local site = w.node and w.node[ant.at]
          if site and site.owner == "you" then hostile = true; break end
        end
      end
    end
    if not hostile and w.locs then
      -- PLAN 05, section 7: a spider fight IS a war (the plan's own
      -- words: "a spider fight counts as war -- the skirmish track
      -- plays"). Any spider location with engaged ants and hp > 0,
      -- visible per fog exactly like the two branches above -- the
      -- music is the player's ears, it must not reveal a fight on
      -- unobserved ground. `contested` is what M.fightSpider sets while
      -- ants are engaged with her, the same signal a mound assault uses.
      for i = 1, #w.locs do
        local l = w.locs[i]
        if l.kind == "spider" and (l.hp or 0) > 0 and l.contested
           and l.observed then
          hostile = true
          break
        end
      end
    end
  end
  if hostile then
    tenseFor = TENSE_HOLD
  else
    tenseFor = math.max(0, tenseFor - dt)
  end

  local wantTense = tenseFor > 0
  for key, src in pairs(music) do
    local target = ((key == "tense") == wantTense) and MUSIC_VOL or 0
    local g = musicGain[key] or 0
    local rate = dt / MUSIC_FADE
    if g < target then g = math.min(target, g + rate)
    elseif g > target then g = math.max(target, g - rate) end
    musicGain[key] = g
    ensurePlaying(src, g)
  end

  local want = "spring"

  -- Crossfade the bed. Every season's source keeps playing at whatever gain
  -- it has; only the gains move, so the transition has no seam and the
  -- music never restarts.
  for name, src in pairs(beds) do
    local target = (name == want) and 0.55 or 0
    local g = bedGain[name] or 0
    local rate = dt / CROSSFADE
    if g < target then g = math.min(target, g + rate)
    elseif g > target then g = math.max(target, g - rate) end
    bedGain[name] = g
    -- A bed at zero is left playing but silent rather than stopped: a
    -- stopped source restarts from its head next year, and that seam is
    -- audible.
    ensurePlaying(src, g)
  end
  currentBed = want

  -- Rain rides the sim value directly, with a fade so it arrives and leaves
  -- like weather rather than like a switch.
  --
  -- GUARDED, because `snap.threats` does not exist since the 4X rebuild --
  -- the snapshot carries world/agents/level and nothing else. Reading it
  -- unguarded is what made this whole function crash, and the fix at the
  -- time was a `do return end` at the top, which silently disabled EVERY
  -- sound in the game rather than the one line that was broken. No rain
  -- for now; the beds, weather bed and music all still play.
  local rainT = (snap.threats and snap.threats.rain) or 0
  local rainWant = 0
  if rainT > 0 then
    local dur = require("sim.threats").cfg.rainDur
    rainWant = math.min(1, math.min(rainT, dur - rainT) / 2.5) * 0.7
  end
  M._rain = M._rain or 0
  local r = M._rain
  local step = dt / 1.5
  if r < rainWant then r = math.min(rainWant, r + step)
  else r = math.max(rainWant, r - step) end
  M._rain = r
  ensurePlaying(weather.rain, r)

  -- Wind is always there, quietly, and picks up in autumn and winter --
  -- the two seasons with the least other activity to listen to.
  local windBase = (want == "autumn" or want == "winter") and 0.28 or 0.16
  ensurePlaying(weather.wind, windBase * (1 - r * 0.6))
end

-- ── event hooks ────────────────────────────────────────────────────────
-- Called from main with the sim's own events, so the mix follows the world
-- rather than the interface.

function M.onIntent(kind, ok)
  if kind == "link" or kind == "reinforce" then
    if ok then M.play("link", 0.55) else M.play("refuse", 0.5) end
  elseif kind == "danger" then
    if ok then M.play("link", 0.35) else M.play("refuse", 0.5) end
  elseif kind == "abandon" or kind == "caste" then
    if not ok then M.play("refuse", 0.45) end
  end
end

function M.onWorldEvent(ev)
  if ev.kind == "discover" then
    M.play("discover", 0.6)
  elseif ev.kind == "season" then
    M.play("season", 0.7)
  end
end

-- Delivery is the colony's heartbeat. Rate-limited hard and mixed by how
-- busy things are, so what you hear is the RATE of work rather than each
-- unit of it -- which at 150 ants would be a machine gun.
function M.onActivity(deliveredDelta, ants)
  if deliveredDelta <= 0 then return end
  local busy = math.min(1, deliveredDelta / 60)
  M.play("deliver", 0.10 + busy * 0.22)
end

function M.onThreat()
  M.play("threat", 0.5)
end

return M
